# Generated by Django 5.1.1 on 2024-10-03 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customuser_email_passwordresetcode'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='passwordresetcode',
            unique_together={('email', 'code')},
        ),
    ]
