# Generated by Django 5.1.1 on 2024-10-06 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_customuser_unique_non_null_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordresetcode',
            name='email',
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='passwordresetcode',
            name='user_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
