# Generated by Django 5.1.2 on 2024-11-19 12:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_admin', '0002_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Assessment Categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_category', models.CharField(choices=[('Attention', 'Attention'), ('Organization', 'Organization'), ('Hyperactivity', 'Hyperactivity'), ('Impulsivity', 'Impulsivity'), ('Social Communication', 'Social Communication'), ('Behavior Patterns', 'Behavior Patterns'), ('Social Understanding', 'Social Understanding'), ('Emotional Understanding', 'Emotional Understanding'), ('Academic Performance', 'Academic Performance'), ('Adaptive Functioning', 'Adaptive Functioning'), ('Cognitive Skills', 'Cognitive Skills'), ('Language Development', 'Language Development')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='special_education.assessmentcategory')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='special_education.assessmentcategory')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.studentinfo')),
            ],
            options={
                'unique_together': {('student', 'category', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AssessmentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('never', 'Never'), ('sometimes', 'Sometimes'), ('often', 'Often'), ('very_often', 'Very Often')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='special_education.question')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='special_education.studentassessment')),
            ],
            options={
                'unique_together': {('assessment', 'question')},
            },
        ),
    ]
