# Generated by Django 5.1.2 on 2024-11-19 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_education', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_category',
            field=models.CharField(choices=[('Attention', 'Attention'), ('Hyperactivity', 'Hyperactivity'), ('Impulsivity', 'Impulsivity'), ('Social Communication', 'Social Communication'), ('Behavior Patterns', 'Behavior Patterns'), ('Social Understanding', 'Social Understanding'), ('Emotional Understanding', 'Emotional Understanding'), ('Academic Performance', 'Academic Performance'), ('Cognitive Skills', 'Cognitive Skills'), ('Language Development', 'Language Development'), ('Speech Production', 'Speech Production'), ('Social Skills', 'Social Skills')], max_length=50),
        ),
    ]
