# Generated by Django 5.1.2 on 2024-11-19 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_education', '0002_alter_question_question_category'),
        ('user_admin', '0002_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentassessment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='studentassessment',
            unique_together={('student', 'category')},
        ),
        migrations.AlterField(
            model_name='studentassessment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
