# Generated by Django 5.1.3 on 2024-11-23 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_education', '0004_alter_studentassessment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcategory',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='results_available_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentresponse',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='special_education.studentassessment'),
        ),
    ]
