# Generated by Django 5.1.3 on 2024-11-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_education', '0005_assessmentcategory_is_active_question_is_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentassessment',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='studentassessment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentassessment',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='studentassessment',
            name='assessment_number',
            field=models.IntegerField(default=1),
        ),
    ]
