# Generated by Django 5.1.1 on 2024-11-23 12:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_education', '0006_alter_studentassessment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentassessment',
            name='assessment_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='studentassessment',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
