# Generated by Django 5.1.3 on 2024-11-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_education', '0007_alter_studentassessment_assessment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentcategory',
            name='description_tl',
            field=models.TextField(blank=True, verbose_name='Description (Tagalog)'),
        ),
        migrations.AddField(
            model_name='assessmentcategory',
            name='title_tl',
            field=models.CharField(blank=True, max_length=100, verbose_name='Title (Tagalog)'),
        ),
    ]
