# Generated by Django 5.1.3 on 2024-11-24 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('special_education', '0008_assessmentcategory_description_tl_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text_tl',
            field=models.TextField(blank=True, verbose_name='Question Text (Tagalog)'),
        ),
    ]
