# Generated by Django 5.1.1 on 2024-11-20 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_admin', '0002_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade_level', models.CharField(choices=[('Nursery', 'Nursery'), ('Casa 1', 'Casa 1'), ('Casa 2', 'Casa 2'), ('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3'), ('Grade 4', 'Grade 4'), ('Grade 5', 'Grade 5'), ('Grade 6', 'Grade 6')], max_length=20, null=True)),
                ('class_section', models.CharField(max_length=20, null=True)),
                ('subject_name', models.CharField(choices=[('MORAL', 'Moral'), ('READING', 'Reading'), ('MATH', 'Math'), ('ECLP', 'English Computerized Learning Program'), ('ROBOTICS', 'Robotics'), ('ENGLISH', 'English'), ('SCIENCE', 'Science'), ('FILIPINO', 'Filipino'), ('MOTHER_TONGUE', 'Mother Tongue'), ('ARALING_PANLIPUNAN', 'Araling Panlipunan'), ('MAPEH', 'MAPEH'), ('VALUES_EDUCATION', 'Values Education'), ('HELE', 'Home Economics & Livelihood Education')], max_length=50)),
                ('class_instructor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='user_admin.teacherinfo')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoomStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_date', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_students', to='user_teacher.classroom')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrolled_classrooms', to='user_admin.studentinfo')),
            ],
        ),
    ]
