# Generated by Django 5.1.1 on 2024-11-22 17:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=255)),
                ('material_type', models.CharField(choices=[('ppt', 'Presentation'), ('pdf', 'PDF Document'), ('img', 'Image'), ('vid', 'Video'), ('doc', 'Word Document')], max_length=10)),
                ('file', models.FileField(upload_to='education_materials/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ppt', 'pptx', 'pdf', 'jpg', 'jpeg', 'png', 'mp4', 'avi', 'doc', 'docx'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='user_teacher.classroom')),
            ],
        ),
    ]
