# Generated by Django 5.1.1 on 2024-11-24 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0008_publicinfo'),
        ('user_teacher', '0003_question_choice_quiz_question_quiz_studentresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed')], max_length=10)),
                ('total_score', models.IntegerField()),
                ('total_possible', models.IntegerField()),
                ('percentage_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_scores', to='user_teacher.classroom')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='user_teacher.quiz')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_scores', to='user_admin.studentinfo')),
                ('student_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='score', to='user_teacher.studentresponse')),
            ],
        ),
    ]
