# Generated by Django 5.1.1 on 2024-11-25 12:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_teacher', '0004_quizscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationmaterial',
            name='file',
            field=models.FileField(upload_to='education_materials', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ppt', 'pptx', 'pdf', 'jpg', 'jpeg', 'png', 'mp4', 'avi', 'doc', 'docx'])]),
        ),
    ]
