# Generated by Django 5.1.1 on 2024-11-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_teacher', '0006_alter_educationmaterial_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('single', 'Single Choice'), ('multi', 'Multiple Choice'), ('identification', 'Identification'), ('true_false', 'True or False')], max_length=50),
        ),
    ]
