# Generated by Django 5.1.1 on 2024-12-10 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_teacher', '0008_educationmaterial_cloudinary_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('activity', 'Activity')], default='quiz', max_length=20),
        ),
    ]
