# Generated by Django 5.1.1 on 2024-10-18 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentinfo',
            old_name='user_info',
            new_name='student_info',
        ),
    ]
