# Generated by Django 5.1.1 on 2024-10-18 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user_admin.userinfo')),
                ('student_info', models.ManyToManyField(related_name='parents', to='user_admin.studentinfo')),
            ],
        ),
    ]
