# Generated by Django 5.1.1 on 2024-11-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='contact_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
