# Generated by Django 5.1.2 on 2024-11-20 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='branch',
            field=models.CharField(choices=[('all', 'All'), ('batangas', 'Batangas'), ('rosario', 'Rosario'), ('bauan', 'Bauan'), ('metrotagaytay', 'Metro Tagaytay')], default='all', max_length=50),
        ),
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('students', 'Students'), ('teachers', 'Teachers'), ('parents', 'Parents'), ('all', 'All')], max_length=50)),
                ('branch', models.CharField(choices=[('all', 'All'), ('batangas', 'Batangas'), ('rosario', 'Rosario'), ('bauan', 'Bauan'), ('metrotagaytay', 'Metro Tagaytay')], max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user_admin.event')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
