# Generated by Django 5.1.2 on 2024-11-20 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0003_event_branch_eventnotification'),
    ]

    operations = [
    ]
