# Generated by Django 5.1.1 on 2024-11-13 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0004_alter_studentinfo_grade_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfo',
            name='student_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parentinfo', to='user_admin.studentinfo'),
        ),
    ]
