# Generated by Django 5.1.1 on 2024-11-21 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0005_alter_event_options_remove_eventnotification_branch_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventNotification',
        ),
    ]
