# Generated by Django 5.1.1 on 2024-11-13 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0005_alter_parentinfo_student_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentinfo',
            name='parent_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_info', to='user_admin.userinfo'),
        ),
        migrations.AlterField(
            model_name='parentinfo',
            name='student_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_student', to='user_admin.studentinfo'),
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='student_info',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_info', to='user_admin.userinfo'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to=settings.AUTH_USER_MODEL),
        ),
    ]
