# Generated by Django 5.1.1 on 2024-11-15 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0006_alter_parentinfo_parent_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentinfo',
            name='student_info',
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='student_info',
            field=models.ManyToManyField(related_name='parent_student', to='user_admin.studentinfo'),
        ),
    ]
