# Generated by Django 5.1.3 on 2024-11-22 06:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0006_delete_eventnotification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='event',
            name='attachment',
        ),
        migrations.AlterField(
            model_name='event',
            name='branch',
            field=models.CharField(choices=[('all', 'All'), ('batangas', 'Batangas'), ('bauan', 'Bauan'), ('rosario', 'Rosario')], default='all', help_text='Select the branch for this event', max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='target_audience',
            field=models.CharField(choices=[('admin', 'ADMIN'), ('all', 'All'), ('parent', 'PARENT'), ('student', 'STUDENT'), ('teacher', 'TEACHER')], help_text='Select the target audience for this event', max_length=50),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['target_audience', 'branch'], name='user_admin__target__30ece5_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['date'], name='user_admin__date_d9f72d_idx'),
        ),
        migrations.AddField(
            model_name='eventnotification',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='user_admin.event'),
        ),
        migrations.AddField(
            model_name='eventnotification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventnotification',
            index=models.Index(fields=['user', 'is_read'], name='user_admin__user_id_318db1_idx'),
        ),
        migrations.AddIndex(
            model_name='eventnotification',
            index=models.Index(fields=['created_at'], name='user_admin__created_ce5f07_idx'),
        ),
    ]
