# Generated by Django 5.1.1 on 2024-11-17 04:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0007_remove_parentinfo_student_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_position', models.CharField(max_length=20, null=True)),
                ('teacher_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_info', to='user_admin.userinfo')),
            ],
        ),
    ]
