# Generated by Django 5.1.1 on 2024-11-26 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0008_publicinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='branch',
            field=models.CharField(choices=[('all', 'All'), ('batangas', 'Batangas'), ('bauan', 'Bauan'), ('metro tagaytay', 'Metro Tagaytay'), ('rosario', 'Rosario')], default='all', help_text='Select the branch for this event', max_length=50),
        ),
    ]
