# Generated by Django 5.1.1 on 2024-12-01 12:51

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0009_alter_event_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/profile_images/', location='C:\\Users\\JD\\Documents\\GitHub\\sunhill-repo\\backend\\media\\profile_images'), upload_to='profile_images/'),
        ),
    ]
