# Generated by Django 5.1.1 on 2024-12-02 05:16

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0010_alter_userinfo_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='branch',
            field=models.CharField(choices=[('all', 'All'), ('batangas', 'Batangas'), ('bauan', 'Bauan'), ('rosario', 'Rosario')], default='all', help_text='Select the branch for this event', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/profile_images/', location='C:\\Users\\JD\\Documents\\GitHub\\sunhill-repo\\backend\\media\\profile_images'), upload_to=''),
        ),
    ]
