# Generated by Django 5.1.1 on 2024-12-08 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0011_alter_event_branch_alter_userinfo_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentinfo',
            name='has_special_needs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentinfo',
            name='special_needs_details',
            field=models.TextField(blank=True, help_text='Details of any special needs conditions', null=True),
        ),
    ]
